SPK_NAME = tesseract-ocr
SPK_VERS = 4.1.0
SPK_REV = 1

DEPENDS = cross/${SPK_NAME}

MAINTAINER = SynoCommunity
DESCRIPTION = Open Source OCR Engine
DISPLAY_NAME = Tesseract OCR

CHANGELOG = "Initial version"

HOMEPAGE = https://github.com/tesseract-ocr
LICENSE  = Apache License 2.0

WIZARDS_DIR = src/wizard/

STARTABLE = no
SERVICE_SETUP = src/service-setup.sh


include ../../mk/spksrc.spk.mk
