PKG_NAME = filemagic
PKG_VERS = 1.6
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/f/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

#
DEPENDS = cross/file 

HOMEPAGE = https://filemagic.readthedocs.io/en/latest/
LICENSE  = Apache License 2.0 

include ../../mk/spksrc.python-wheel.mk
