PKG_NAME = stapler
PKG_VERS = 1.0.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/s/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/hellerbarde/stapler
COMMENT  = A small utility making use of the pypdf library to provide a (somewhat) lighter alternative to pdftk
LICENSE  = Copyright (c) 2009, Philip Stark, Fred Wenzel

include ../../mk/spksrc.python-wheel.mk