PKG_NAME = mglib
PKG_VERS = 5edd196aaa1fe710ac5742048b1e252a38e3587c
PKG_EXT = zip
PKG_DIST_NAME = $(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/papermerge/mglib/archive/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/papermerge/mglib/
COMMENT  = tbc
LICENSE  = Apache-2.0 License

DEPENDS = cross/stapler

include ../../mk/spksrc.python-wheel.mk