PKG_NAME = mglib
PKG_VERS = ac7f2ae37b3f32e8394b7616c53d3c355a9c1e86
PKG_EXT = zip
PKG_DIST_NAME = $(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/papermerge/mglib/archive/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/papermerge/mglib/
COMMENT  = tbc
LICENSE  = Apache-2.0 License

DEPENDS = cross/stapler

include ../../mk/spksrc.python-wheel.mk